FormidableLabs/react-live

src/components/Editor/index.js, src/components/Live/LiveEditor.js
This allows for passing props into the editor from the wrapping app.
=> Enable rest props to pass to editor

src/components/Editor/index.js
As-is, the editor does not update its code when it receives new code in props.
Instead, it sets the code to the last value, instead of the next value.
=> Update code from props correctly

README.md, src/components/Editor/index.js, typings/react-live.d.ts
This adds a prop to `Editor` to allow you to disable the tab key handling. The default behavior is nice for a lot of cases, but it's a focus trap for keyboard users navigating through a page with an editor in it.
=> Add option to ignore editor tab key handling

README.md, src/components/Live/LiveEditor.js
This fixes a warning in dev about an "invalid prop type" - It looks like a small oversight writing `function` rather than `func`.
cc @philpl
=> Fix invalid onChange prop type error

README.md, src/components/Live/LiveProvider.js
Optionally provide a function to transform the code input, before it gets transpiled. Invisible to the user.
eg:
```
const serverSafe = (code) => `
if (typeof document !== 'undefined' && typeof window !== 'undefined') {
${code}
}
`;
<LiveProvider transformCode={serverSafe} />
```
=> Adding `transformCode` prop to `LiveProvider`

src/components/Editor/index.js
**what is the change?:**
Add `spellCheck="false"` to the `contenteditable` container of the
editor.
**why make this change?:**
In Firefox and probably other places, words that are flagged by the
browser as misspelled will have a dotted underline. This really stands
out in the editor and is distracting, not relevant for code.
**test plan:**
Manual testing - 
*before*
*after*
**issue:**
https://github.com/FormidableLabs/react-live/issues/30
=> Disable spellcheck in editor

src/components/Editor/index.js
React 16 warns and ignores boolean values in non-boolean
attributes. React 15 converted these to strings and passed
through. Replacing logical operators with ternary in attributes
removes the warning.
https://github.com/alexkuz/react-json-tree/issues/94
https://facebook.github.io/react/blog/2017/09/08/dom-attributes-in-react-16.html
While using the react-live Editor in a React 16 application, console warned the following for `onKeyUp`, `onKeyDown`, and `onClick`:
```
Warning: Expected `onKeyDown` listener to be a function, instead got a value of `boolean` type.
in pre (created by Editor)
in Editor (created by LiveEditor)
in LiveEditor (created by Styled(LiveEditor))
in Styled(LiveEditor) (created by MapCode)
in div (created by LiveProvider)
in LiveProvider (created by …
```
=> Remove boolean values from non-boolean attributes for React 16

README.md
**Issue:**
https://react-live-demo.philpl.com/ redirects to https://zeit.co/philpl/react-live-demo/dxdmjnnurj?redirect=1 where we get a 403.
**Solution:**
Updating the link to https://react-live.philpl.com/
=> [fix] Demo link leading to 403 page

src/components/Editor/index.js
Using the `ignoreTabKey` prop causes a warning to be logged to the console in React 16:
> Warning: React does not recognize the `ignoreTabKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ignoretabkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
This is because `LiveEditor` [spreads all props](https://github.com/FormidableLabs/react-live/blob/34290462caa206ffac7accb2afcdb908a4975457/src/components/Live/LiveEditor.js#L8) to `Editor` which [does the same](https://github.com/FormidableLabs/react-live/blob/34290462caa206ffac7accb2afcdb908a4975457/src/components/Editor/index.js#L204) to its child `<pre>` tag.
The simplest fix for this is to explicitly remove that prop …
=> Remove ignoreTabKey prop before spreading rest to <pre>

package.json, yarn.lock
Resolves https://github.com/FormidableLabs/react-live/issues/49
FWIW, the only code-changes to _dom-iterator_ from `v0.0.3` to `v1.0.0` were the bugfix for the issue and documentation-edits.
=> Upgrades dom-iterator to 1.0.0

.storybook/addons.js, .storybook/config.js, jest.setup.js, package.json, src/components/Live/LivePreview.js, src/components/Live/LiveProvider.js, src/utils/test/errorBoundary.test.js, src/utils/test/transpile.test.js, src/utils/transpile/errorBoundary.js, stories/Editor.js, stories/Live.js, yarn.lock
Since React 16 is required for `componentDidCatch`, I've upgraded the React dev dep to v16 (and bumped some other deps to latest as a result, including storybook).
Adding an error boundary to `LiveProvider` directly caused some problems (catching an error with it would cause the inner `LiveEditor` to be reset to the initial code provided via props + the editor would lose focus) so I instead opted to wrap the element received from `renderElement` with a small component that provides an error boundary.
I left the original error boundary code intact but I'm happy to clean that up if it's no longer necessary, let me know what you think.
=> Use React 16 error boundaries to catch errors from components included via scope

src/components/Live/LiveProvider.js
A small fix that prevents `scope` prop from getting on the `div` DOM node. Right now it looks like this:
I'm not sure if this was intentional or not. If it was, sorry for bothering 😅
=> Prevent scope from getting on 'react-live' DOM node

src/hoc/withLive.js
Fixes https://github.com/FormidableLabs/react-live/issues/48
=> Pass through all props in withLive HOC

package.json, src/components/Live/LiveEditor.js, src/components/Live/LiveError.js, src/components/Live/LivePreview.js, src/components/Live/LiveProvider.js, src/hoc/withLive.js, stories/Live.js, yarn.lock
The current implementation can't propagate updates through a PureComponent wrapper, which is one of the nice improvements of v16 context.
=> upgrade to use React v16 context, polyfill for older Reacts

README.md, stories/Live.js
Documentation now reflects recent API changes. Added a FAQ section that has a example using `transformCode` and `babel` (fixes #93)
=> Update documentation to reflect recent changes

src/components/Editor/index.js, src/components/Live/LiveProvider.js, stories/Live.js
Fixes: 
- `onChange` being called twice #127 
- code changes lagging behind one update cycle #130 
- raw events being bubbled to `LiveProvidesr` `onChange/transformCode`  #126
=> Fix onChange related errors

src/components/Live/LiveProvider.js
noticed here: https://github.com/react-bootstrap/react-bootstrap/pull/3631
Since this commit: https://github.com/FormidableLabs/react-live/commit/a7f0cf144897392abbcbfd35026c769649c53811#diff-c4542d3ce4efdafdf35660d1c7f57a33L105 LiveProvider is not anymore a `div`. So styling is not possible anymore. As a workaround the children can be wrapped into a `div` with styles e.g. Styled Components.
=> fix: removed unused className on LiveProvider

typings/react-live.d.ts
We can get rid of `Component` in favor of `ComponentType` defined in `@types/react`.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L74
TypeScript 2.8 adds Exclude
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#predefined-conditional-types
=> Remove redundant types

typings/react-live.d.ts, typings/test.tsx
I've updated `type LiveProviderProps` to match the table in README.md and PropTypes.
https://github.com/FormidableLabs/react-live/blob/master/src/components/Live/LiveProvider.js#L15
https://github.com/FormidableLabs/react-live#liveprovider-
https://github.com/FormidableLabs/prism-react-renderer#theming
=> Update LiveProviderProps type

src/components/Editor/index.js, stories/Live.js
Fix for issue #139. 
Will remove the commented out line on `68` of `Editor/index.js` before removing `WIP` status.
I thought it could make the most sense to pass in everything from `theme.plain` as the element-level style, meaning that - if no `theme` prop is used, we don't add anything, rather than defaulting to a base theme, as people might not expect this/it might get frustrating for people just using styled components.
=> Handle optional `theme.plain` object, add storybook example #139

.eslintignore, .eslintrc, .sail.yml, .storybook/addons.js, demo/components/Header.js, demo/components/LiveEdit.js, demo/server.js, package.json, rollup.config.js, src/components/Editor/index.js, src/components/Live/LiveProvider.js, src/index.js, src/utils/test/errorBoundary.test.js, src/utils/test/transpile.test.js, src/utils/transpile/errorBoundary.js, src/utils/transpile/evalCode.js, src/utils/transpile/index.js, src/utils/transpile/transform.js, stories/Editor.js, stories/Live.js, yarn.lock
1. Added prettier + script.
1. Added EsLint + base formidable config + script.
1. Fixed eslint errors.
1. Added sail ci config.
=> CI/CD Setup

src/components/Editor/index.js
Fixes `theme is not defined` error in latest release
=> Fix `theme is not defined` ReferenceError by passing theme prop

package.json
Version 0.2.3 of `create-react-context` does not have an MIT license. As a result, many companies are unable to use `react-live`. Between v0.2.2 and v0.2.3 only the license and the README has changed, it is safe to depend on `v0.2.2` rather than `v0.2.3`.
=> Update the version of create-react-context

rollup.config.js
This PR fixes prism-react-renderer from being included in the dist. 
1. Rename references to prismjs -> prism-react-renderer.
Reduces bundled code size to 7.26 KB.
=> Removes prism-react-renderer from the bundle

README.md
Fix #149 
This adds a note to the readme of what bundle size we can expect when adding `react-live` to an application and how to reduce it.
=> Add README note about bundlesize

src/utils/test/transpile.test.js, src/utils/transpile/index.js
Prevents the application from breaking if `render` is called while `noInline` is true (see: https://github.com/FormidableLabs/react-live/issues/151)
Example (after changes):
=> Safely catch calls with empty render. Fixes #151

README.md
The old link (https://react-live.kitten.sh/) seems broken and https://react-live.netlify.com/ is already present in the repository description header.
=> Fix: Update demo link in README.md

typings/react-live.d.ts, typings/test.tsx
The component was [exported already](https://github.com/FormidableLabs/react-live/blob/master/src/index.js#L20) this just add it to the type defs
=> Add LiveContext typings

demo/package.json
In demo/package.json，I use next directly.
And I delete next.config.js because running demo doesn't need it.
=> fix: demo start scripts

package.json, src/components/Live/LiveContext.js, yarn.lock
* `create-react-context` uses a version of `fbjs` that includes a vulnerable version of `node-fetch`.
* This PR updates `create-react-context` to the latest version.
* `@storybook/react` and `@storybook/addon-knobs` also use a version of `fbjs` that includes the vulnerable `node-fetch` version, but these are dev dependencies that should not impact production usage of `react-live` anywhere.
I tested by starting Storybook locally and ensuring that each case still renders as expected.
=> Update create-react-context, fixes #221

demo/.eslintrc, demo/netlify.toml, demo/next.config.js, demo/package.json, demo/pages/index.js, demo/yarn.lock
- closes https://github.com/FormidableLabs/react-live/pull/249
- closes https://github.com/FormidableLabs/react-live/pull/245
- closes https://github.com/FormidableLabs/react-live/pull/242
- closes https://github.com/FormidableLabs/react-live/pull/238
- closes https://github.com/FormidableLabs/react-live/pull/235
- closes https://github.com/FormidableLabs/react-live/pull/227
=> update demo site

src/components/Editor/index.js
- squashes a bug inadvertently introduced when https://github.com/FormidableLabs/react-live/pull/226 was merged
- previously we were removing `onChange` (and a few other props) before spreading the `...rest` remainder down to `react-simple-code-editor`
- `onChange` gets called with a `SyntheticEvent` (instead of a value) and that in turns throws a bunch of other errors
- as a fix i considered removing the props spread entirely and just being more explicit, but it seems like this was originally introduced to (optionally) support spreading handlers like `onFocus` and `onBlur` down to the editor (see https://github.com/FormidableLabs/react-live/pull/6)
- in the interest of not interfering with event handler spreading, I've just restored the behaviour prior to #226 which was just to swallow …
=> remove onChange prop again before spreading to react-simple-code-editor

src/components/Editor/index.js, src/components/Live/LiveEditor.js, src/components/Live/LiveError.js, src/components/Live/LivePreview.js
- following https://github.com/FormidableLabs/react-live/pull/226, this PR migrates the default `Editor` to be a functional component that uses Hooks rather than a `class`
- similarly, Hooks are now used to consume Context in:-
- `LiveEditor`
- `LiveError`
- `LivePreview`
- this may potentially prepare us for https://github.com/FormidableLabs/react-live/issues/254
- small impact on bundle sizes:
=> migrate other Live components to fn components

package.json, src/components/Live/LiveProvider.js, src/utils/test/transpile.test.js, src/utils/transpile/index.js, src/utils/transpile/transform.js, typings/react-live.d.ts, yarn.lock
Closes #252
Now it's possible to adjust buble transformations by passing transpileOptions prop to LiveProvider. 
Example
```jsx
<LiveProvider
transpileOptions={{
transforms: {
classes: false,
asyncAwait: false
}
}}
// ...
```
See the list of bubble transforms here: https://buble.surge.sh/guide/#command-line-options
=> feat: add transpileOptions prop to LiveProvider

src/utils/transpile/errorBoundary.js
[https://github.com/FormidableLabs/react-live/issues/283](url)
Add a React.isValidElement check before rendering to the live playground, preventing a full window crash when entering non-valid child objects such as console, window, document.
See the difference in changes below:
Before - https://www.loom.com/share/ba67749226a546129caa8cc7e33eae09
After - https://www.loom.com/share/0583ebbaaf6c4ccf8f69eaca1a35c9ad
resolves #283
=> fix #283: Verify valid element before rendering

README.md
Very small PR that updates the images in the README to use https rather than http. These images were causing some netlify checks to fail downstream on formidable.com
=> Update images in README to use https

jest.setup.js, package.json, src/utils/test/errorBoundary.test.js, src/utils/test/renderer.js, src/utils/test/transpile.test.js, yarn.lock
- ditches `enzyme` in favour of `react-testing-library` and `react-dom`
- instead of having to use the [unofficial enzyme adapter for React 17](https://github.com/wojtekmaj/enzyme-adapter-react-17)
- should be released as part of `v3.0` in tandem with https://github.com/FormidableLabs/react-live/pull/266 
> invalid: "^16.0.0" from node_modules/react-simple-code-editor
- or can go as a `v2.x` release if https://github.com/satya164/react-simple-code-editor/issues/75 is merged first
- (either way we'll ultimately move away from `react-simple-code-editor`)
=> upgrade to React 17

package.json, rollup.config.js, yarn.lock
- remove `@types/buble` and `buble` following transition to `sucrase`
- remove `dom-iterator` and `unescape` (no longer needed)
- move `prop-types` to be a `devDependency` and tweak Rollup config to fully exclude it
=> cleanup dependencies

package.json, src/components/Editor/index.js, stories/Editor.js, typings/react-live.d.ts, yarn.lock
I am upgrading the website for the Emotion project to the latest react-live. We need to pass in a custom Prism instance that highlights CSS embedded in JS tagged template literals. This PR makes it so you can pass in a custom Prism instance.
Closes #284.
=> Add prism prop to Editor

package.json, src/components/Live/LiveProvider.js, src/components/Live/LiveProvider.test.js, typings/react-live.d.ts
Hello, I am upgrading the website for the Emotion project to the latest react-live. This PR fixes two issues I encountered with `transformCode`:
- `transformCode` did not support asynchronous functions. We need this because we do our transformation in a web worker to avoid blocking the UI thread.
- react-live did not handle errors thrown by `transformCode`. If the user enters invalid code, it is very likely that `transformCode` will throw. Closes https://github.com/FormidableLabs/react-live/issues/233.
- Also, the prop type for `transformCode` was wrong.
=> Support async transformCode, catch transformCode errors

src/components/Editor/index.js
- fixes https://github.com/FormidableLabs/react-live/issues/310
- fixes https://github.com/FormidableLabs/react-live/issues/315
=> add spellCheck=false to stop Editor underlining code

README.md, src/components/Editor/index.js, typings/react-live.d.ts
This pull request adds a new prop for LiveEditor - `tabMode` - which lets you define how the tab key should work.
If you pass the value `indentation` (the default), everything will work as it has. If you pass `focus`, however, you'll be able to tab on to the next or previous item in the tab order, which is a WCAG requirement.
You could then implement a way to change this mode based on user settings, an external checkbox or whatever, really.
Fixes #179
=> Add tabMode prop

src/components/Editor/index.js, stories/Live.js
**Status**: WIP -- we don't have great test coverage here, so I'm mostly manually looking at Storybooks. Would love some more eyes on if anything _else_ changes from this feature.
We changed how the theme / style applies [here](https://github.com/FormidableLabs/react-live/commit/2265d8dbca01631486f89de3b50753ead160d41c#diff-36a5a8b972ef005a146943557d3eda53686dd70c19c4da1c7c8a3c5301c8e17bL55-R47). If I'm reading this correctly, we originally detected if a base theme was provided on props, then applied that, then overrode with styles coming after.
See https://github.com/FormidableLabs/react-live/issues/303
I've tried to re-implement the original theme overriding behavior. And I've tweaked the default live example to take in the theme object.
- The default live example now shows a different …
=> Fix: Apply theme changes.

.github/workflows/code-check.yml, .gitignore, .storybook/main.js, package.json, yarn.lock
Using Storybook + webpack 4 on Node 17+ caused a familiar error: `digital envelope routines::unsupported`. This upgrades the dependencies to webpack 5 for Storybook only to allow it to run on modern Node.
Also adds a base GitHub actions flow to check lint, unit tests, and building of the library and storybook.
=> Upgrade Storybook to use webpack 5 + GitHub actions

.changeset/config.json, .github/workflows/release.yml, package.json, yarn.lock
=> Add changesets to React Live

.github/workflows/deploy-docs.yml, README.md, docs/introduction.mdx, website/docusaurus.config.js, website/formideploy.config.js, website/package.json, website/yarn.lock
Sets up the pipeline to deploy our docs site to `formidable.com/open-source/react-live`
=> Set up Formideploy for Docusarus site

.github/workflows/release.yml, package.json
Adding [NPM package provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) for react-live releases
=> Setting up NPM Provenance

.changeset/nice-ligers-leave.md, packages/react-live/src/components/Live/LivePreview.tsx
Implementing #349 on the new directory structure and adding a changeset
👇🏻 see the two different usages
=> Fix live preview types

.changeset/shiny-jeans-matter.md, package.json, packages/demo/index.html, packages/demo/package.json, packages/demo/postcss.config.cjs, packages/demo/src/app.tsx, packages/demo/src/index.css, packages/demo/src/main.tsx, packages/demo/src/vite-env.d.ts, packages/demo/tailwind.config.cjs, packages/demo/tsconfig.json, packages/demo/vite.config.ts, packages/react-live/package.json, packages/react-live/src/components/Editor/index.tsx, pnpm-lock.yaml
- Adds Vite-based demo app to test dev on this project
- Fixes the cursor position on a new line by ensuring all elements in the editor tree are span, div causes the cursor to bounce, css ensures each line-token is rendered on its own line. as seen in #343
To test:
Run the `dev:demo` task after building the library and recreate the above. The cursor should follow the new line.
=> Fix cursor position on new line, add demo app

.changeset/fair-glasses-protect.md, packages/react-live/src/components/Editor/index.tsx
`.trim()` removed all ability to insert a new line. We want to just splice out the last character instead so a new carriage return can be added.
https://github.com/FormidableLabs/react-live/assets/1738349/0f081ce0-d19e-4187-8d01-c26e3ef156c5
=> Fix ability to insert a new line at the end of the editor.

.changeset/tasty-camels-smell.md, package.json, packages/react-live/package.json, pnpm-lock.yaml
We missed the peer deps for React in this library, this adds those in and sets `prism-react-renderer` version explicitly in root and the library package.
=> Set peer deps for React, fix PRR version

.changeset/popular-pumas-beam.md, packages/react-live/src/components/Editor/index.tsx
=> Remove Default props

packages/react-live/src/utils/test/fixtures/optional-chain.test.js, packages/react-live/src/utils/transpile/index.ts
Solve this https://github.com/FormidableLabs/react-live/issues/381
When Sucrase compiles the optional chaining syntax, it generates a function called _optionalChain. If we wrap it with a return statement during the first transform, it can lead to certain issues.
This is the output after the first transform and wrapping with a return. Clearly, it's no longer a valid JavaScript syntax. To solve this problem, we can move the wrapReturn to after the second transform
```tsx
return (function _optionalChain(ops) { let lastAccessLHS = undefined; let value = ops[0]; let i = 1; while (i < ops.length) { const op = ops[i]; const fn = ops[i + 1]; i += 2; if ((op === 'optionalAccess' || op === 'optionalCall') && value == null) { return undefined; } if (op === 'access' || op === 'optionalAccess') { …
```
=> Fix: mv wrapReturn behind transform

CONTRIBUTING.MD
The CONTRIBUTING.md docs have references to yarn commands, but the project does not contain a yarn.lock. I assume it was migrated to pnpm from yarn and these docs became stale. I have updated the commands.
=> Replace instances of yarn with pnpm in CONTRIBUTING.md

packages/react-live/src/components/Editor/index.tsx
=> fix: move onchange inside event handler

.changeset/grumpy-schools-rhyme.md, package.json, pnpm-lock.yaml
Use corepack to prevent mistakes when generating lockfiles as happened in #394. Fixes the incorrect lockfile and adds a missing changeset from #393
=> Fix lockfile and use corepack

.changeset/silent-ads-sell.md, .github/workflows/code-check.yml, .github/workflows/release.yml, package.json, packages/react-live/src/components/Live/ErrorBoundary.tsx, packages/react-live/src/components/Live/LiveContext.ts, packages/react-live/src/components/Live/LivePreview.tsx, packages/react-live/src/components/Live/LiveProvider.tsx, website/package.json
React-Live did not catch a runtime error (not caught in the transpile phase).
We can't catch all errors (like event handlers) but we can catch `useEffect`'s cleanup functions.
Fixes #388 
https://github.com/user-attachments/assets/7fa18a71-e688-406b-aa98-9f526518fa43
The above video demonstrates, not a cleanup function not causing crash.
Worth noting, cleanup function runs one cycle "behind", therefore even if we correct the code the previous code with error still shows up.
=> fix: wrap preview in boundary

.changeset/chilled-rats-collect.md, packages/react-live/package.json, pnpm-lock.yaml
Update runtime deps to latest.
- Sucrose - minor fixes for some newer TS syntax [3.31 -> 3.35 Changelog](https://github.com/alangpierce/sucrase/blob/main/CHANGELOG.md)
- Prism - Additional themes and lang support [2.0.6 -> 2.4.0 Changelog](https://github.com/FormidableLabs/prism-react-renderer/releases)
=> Update runtime deps to latest
